var _base = [
	{name: 'Anaconda', tags: ['bl1', 'legendary', 'pistol', 'dahl'], flavor: 'Long and Strong', image_src: ''},
	{name: 'Bastard' , tags: ['bl1', 'legendary', 'machinegun', 'torgue'], flavor: 'TORGUE! Bastard guns for Bastard People!', image_src: ''},
	{name: 'Bitch'   , tags: ['bl1', 'legendary', 'smg', 'hyperion'], flavor: 'Smack\'em', image_src: ''},
	{name: 'Bulldog' , tags: ['bl1', 'legendary', 'shotgun', 'dahl'], flavor: 'One Bad Dog!', image_src: ''},
	{name: 'Butcher' , tags: ['bl1', 'legendary','shotgun', 'hyperion'], flavor: 'Ahhh... Fresh meat !', image_src: ''},
	{name: 'Chimera' , tags: ['bl1', 'legendary','pistol', 'atlas'], flavor: 'A beast of many forms - Fire, Lightning and Poison', image_src: ''},
	{name: 'Cobra'   , tags: ['bl1', 'legendary','sniper', 'torgue'], flavor: 'I LIKE IT', image_src: ''},
	{name: 'Crux'    , tags: ['bl1', 'legendary','shotgun', 'maliwan'], flavor: 'Cross their heart, hope they die.', image_src: ''},
	{name: 'Crux'    , tags: ['bl1', 'legendary','shotgun', 'sands'], flavor: 'Bring out your dead.', image_src: ''},
	{name: 'Cyclops' , tags: ['bl1', 'legendary','sniper', 'atlas'], flavor: 'I have you in my eye, sir.', image_src: ''},
	{name: 'Defender', tags: ['bl1', 'legendary','shotgun', 'tediore'], flavor: 'I can do this all day...', image_src: ''},
	{name: 'Defiler' , tags: ['bl1', 'legendary','pistol', 'maliwan'], flavor: 'Give Sick', image_src: ''},
	{name: 'Destroyer', tags: ['bl1', 'legendary','rifle', 'hyperion'], flavor: 'The destructor has come', image_src: ''},
	{name: 'Draco'   , tags: ['bl1', 'legendary','machinegun','sands'], flavor: '', image_src: ''},
	{name: 'Equalizer', tags: ['bl1', 'legendary','pistol', 'tediore'], flavor: 'Unending firepower', image_src: ''},
	{name: 'Eridian Firebomb', tags: ['bl1', 'legendary','rifle', 'eridian'], flavor: '"Bad is Good BABY!"', image_src: ''},
	{name: 'Eridian Mega Cannon', tags: ['bl1', 'legendary','rifle', 'eridian'], flavor: '010011110100110101000111', image_src: ''},
	{name: 'Eridian Stampeding Spatter Gun', tags: ['bl1', 'legendary','rifle', 'eridian'], flavor: 'For when you want to splat the living shit out of something', image_src: ''},
	{name: 'Firehawk', tags: ['bl1', 'legendary','pistol', 'maliwan'], flavor: 'Bring the HEAT!', image_src: ''},
	{name: 'Friendly Fire', tags: ['bl1', 'legendary','torgue', 'shotgun'], flavor: 'Have a nice day!', image_src: ''},
	{name: 'Gasher'  , tags: ['bl1', 'legendary','smg', 'torgue'], flavor: 'Tear it up!', image_src: ''},
	{name: 'Gemini'  , tags: ['bl1', 'legendary','pistol', 'sands'], flavor: 'Double Whammy.', image_src: ''},
	{name: 'Guardian', tags: ['bl1', 'legendary','rifle', 'tediore'], flavor: 'Hold your ground... Forever', image_src: ''},
	{name: 'Hammer'  , tags: ['bl1', 'legendary','shotgun', 'vladof'], flavor: 'Drop the Hammer!', image_src: ''},
	{name: 'Hellfire', tags: ['bl1', 'legendary','smg', 'maliwan'], flavor: 'We don\'t need no water...', image_src: ''},
	{name: 'Hornet'  , tags: ['bl1', 'legendary', 'pistol', 'dahl'], flavor: 'Feel the Sting', image_src: ''},
	{name: 'Hydra'   , tags: ['bl1', 'legendary', 'shotgun', 'atlas'], flavor: 'Five heads of Death', image_src: ''},
	{name: 'Invader' , tags: ['bl1', 'legendary', 'pistol', 'hyperion'], flavor: '12 bullets invade your skull', image_src: ''},
	{name: 'Invader' , tags: ['bl1', 'legendary', 'rifle', 'hyperion'], flavor: 'BAM BAM BAM BAM BAM!', image_src: ''},
	{name: 'Mongol'  , tags: ['bl1', 'legendary', 'rockets', 'vladof'], flavor: 'Beware the Horde!', image_src: ''},
	{name: 'Nidhogg' , tags: ['bl1', 'legendary', 'rockets', 'hyperion'], flavor: 'Death rains from above', image_src: ''},
	{name: 'Ogre'    , tags: ['bl1', 'legendary', 'smg', 'atlas'], flavor: 'Ogre SMASH!', image_src: ''},
	{name: 'Orion'   , tags: ['bl1', 'legendary', 'rifle', 'sands'], flavor: 'A hunter lives among the stars...', image_src: ''},
	{name: 'Penetrator', tags: ['bl1', 'legendary', 'rifle', 'dahl'], flavor: 'Sniper Killer... Qu\'est que c\'est', image_src: ''},
	{name: 'Protector', tags: ['bl1', 'legendary', 'pistol', 'tediore'], flavor: 'Ammo is no longer an issue', image_src: ''},
	{name: 'Raven'   , tags: ['bl1', 'legendary', 'rifle', 'dahl'], flavor: '2 more bullets make all the difference', image_src: ''},
	{name: 'Reaper'  , tags: ['bl1', 'legendary', 'pistol', 'hyperion'], flavor: 'Slice Slice', image_src: ''},
	{name: 'Rebel'   , tags: ['bl1', 'legendary', 'pistol', 'vladof'], flavor: 'Never stop shooting!', image_src: ''},
	{name: 'Redemption', tags: ['bl1', 'legendary', 'rockets', 'torgue'], flavor: 'Monster Kill!', image_src: ''},
	{name: 'Revolution', tags: ['bl1', 'legendary', 'smg', 'vladof'], flavor: 'Guns of the Revolution will never fall silent!', image_src: ''},
	{name: 'Rhino'   , tags: ['bl1', 'legendary', 'rockets', 'maliwan'], flavor: 'The Unstoppable Force', image_src: ''},
	{name: 'Savior'  , tags: ['bl1', 'legendary', 'smg', 'tediore'], flavor: 'Hallelujah', image_src: ''},
	{name: 'Skullmasher', tags: ['bl1', 'legendary', 'rifle', 'jakobs'], flavor: 'Makes their brain hurt', image_src: ''},
	{name: 'Striker' , tags: ['bl1', 'legendary', 'shotgun', 'jakobs'], flavor: 'Sniper Rifles are for chumps', image_src: ''},
	{name: 'Surkov'  , tags: ['bl1', 'legendary', 'rifle', 'vladof'], flavor: 'For the Motherland.', image_src: ''},
	{name: 'Thanatos', tags: ['bl1', 'legendary', 'pistol', 'sands'], flavor: 'Big Tony says "Hi"', image_src: ''},
	{name: 'Troll'   , tags: ['bl1', 'legendary', 'pistol', 'atlas'], flavor: 'Pain Heals.', image_src: ''},
	{name: 'Unforgiven', tags: ['bl1', 'legendary', 'pistol', 'jakobs'], flavor: 'It\'s a helluva thing...', image_src: ''},
	{name: 'Vengeance', tags: ['bl1', 'legendary', 'pistol', 'vladof'], flavor: 'Vengeance is Yours', image_src: ''},
	{name: 'Violator', tags: ['bl1', 'legendary', 'pistol', 'torgue'], flavor: 'Your move, Creep.', image_src: ''},
	{name: 'Volcano' , tags: ['bl1', 'legendary', 'sniper', 'maliwan'], flavor: 'Pele demands a sacrifice!', image_src: ''},
	{name: 'Wildcat' , tags: ['bl1', 'legendary', 'smg', 'dahl'], flavor: 'The ultimate close quarters feline.', image_src: ''},
	{name: 'Baby Maker', tags: ['bl2', 'legendary', 'smg', 'tediore'], flavor: 'Who\'s a widdle gunny wunny!!!', image_src: ''},
	{name: 'Badaboom', tags: ['bl2', 'legendary', 'rockets', 'bandit'], flavor: 'Multi-kill.', image_src: ''}
]	